spring:
  config:
    import: optional:application-secret.yml
  profiles:
    active: development
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: GOOGLE_CLIENT_ID
            client-secret: GOOGLE_CLIENT_SECRET
            scope:
              - email
              - profile
            redirect-uri: "http://54.180.30.17.nip.io:8080/login/oauth2/code/google"
